In [9]:
import numpy as np

# Generate random vector of size 15 with integers in range 1-20
random_vector = np.random.randint(1, 21, size=15)

# Reshape the vector to 3 by 5 array
reshaped_array = random_vector.reshape(3, 5)

# Replace max in each row by 0
reshaped_array[np.arange(3), np.argmax(reshaped_array, axis=1)] = 0

# Create a 2-dimensional array of size 4 x 3 with 4-byte integer elements
array_4x3 = np.zeros((4, 3), dtype=np.int32)

# Print shape, type, and data type of the array
print("Shape of 2D array:", array_4x3.shape)
print("Type of the array:", type(array_4x3))
print("Data type of the array:", array_4x3.dtype)


Shape of 2D array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array: int32


In [10]:
import numpy as np

# Define the square array
A = np.array([[3, -2],
              [1, 0]])

# Compute the eigenvalues and right eigenvectors
eigenvalues, right_eigenvectors = np.linalg.eig(A)

# Print the eigenvalues and right eigenvectors
print("Eigenvalues:")
print(eigenvalues)
print("\nRight eigenvectors:")
print(right_eigenvectors)


Eigenvalues:
[2. 1.]

Right eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [11]:
array = [[0, 1, 2],
         [3, 4, 5]]

diag_sum = sum(array[i][i] for i in range(min(len(array), len(array[0]))))

print("Sum of diagonal elements:", diag_sum)


Sum of diagonal elements: 4


In [15]:
import numpy as np

# Original array
array1 = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

array2 = np.array([[1, 23],
                   [4, 5],
                   [6, 7]])

# Reshape without changing data
reshaped_array1 = np.reshape(array1, (2, 3))
reshaped_array2 = np.reshape(array2, (3, 2))

# Print reshaped arrays
print("Reshaped 3x2 array:")
print(reshaped_array1)
print("\nReshaped 2x3 array:")
print(reshaped_array2)


Reshaped 3x2 array:
[[1 2 3]
 [4 5 6]]

Reshaped 2x3 array:
[[ 1 23]
 [ 4  5]
 [ 6  7]]
